apiVersion: apps/v1
kind: Deployment
metadata:
  name: aidlc-maintenance
  namespace: aidlc-demo
  labels:
    app: aidlc-maintenance
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aidlc-maintenance
  template:
    metadata:
      labels:
        app: aidlc-maintenance
        version: v1
    spec:
      imagePullSecrets:
      - name: ukad-docker-registry
      containers:
      - name: maintenance
        image: ukad/aidlc-maintenance:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
