apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app-sample
  namespace: default
  labels:
    app: dotnet-app-sample
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-app-sample
  template:
    metadata:
      labels:
        app: dotnet-app-sample
        version: v1.0.0
    spec:
      containers:
      - name: dotnet-app-sample
        image: dotnet-app-sample:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: https
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080;https://+:8081"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
